### ISSUE TITLE
Select with multiple Options only returns the first value

### ISSUE THREAD

**Issue by ghost** [NickMaev/NSerializeJson#1]
Hi,

when serializing a Form containing a select field with multiple selected values, the js object only contains the first value.

This is (part of) the form from the documentation:
```html
<form id="my-profile">
  <!-- select multiple options, just name it as an array[] -->
  <select multiple name="selectMultiple[]">
    <option value="red"  selected>Red</option>
    <option value="blue" selected>Blue</option>
    <option value="yellow">Yellow</option>
	</select>
</form>
```

When serialized it should return
```javascript
{
  selectMultiple: ["red", "blue"]
}
```

instead it returns:
```javascript
{
  selectMultiple: ["red"]
}
```

See also: https://jsfiddle.net/ca2qo9zb/

**Comment by Blackvz** [comment]
The problem also concerns me...

I hope for a quick solution :/ @NickMaev

**Comment by NickMaev** [comment]
Hello guys.
WIP.
Will be fixed ASAP.

**Comment by NickMaev** [comment]
Fixed.

1) selectMultiple, selectMultiple[] will have the same behaviour on multiple select;
2) selectMultiple[]:number will return array of numbers on multiple select.

Try to update to v. **1.0.32-alpha.1**

Awaiting your feedback.

**Comment by Blackvz** [comment]
Thanks for the quick fix. I will try it out later 👍🏻

**Comment by ghost** [comment]
Sorry I was a bit swamped and could not test it right away.
Works like a charm though, thx a bunch for the fast response.
